services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - obtech-odoo-proxymanager-network
  odoo:
    build:
      context: ./infrastructure/odoo
      dockerfile: Dockerfile
    container_name: obtech_odoo
    #command: --dev all --log-level debug
    depends_on:
      - db
    volumes:
      - obtech-odoo-data:/var/lib/odoo
      - ./data/odoo/config-prod:/etc/odoo
      - ./data/odoo/addons:/mnt/extra-addons
      - ./data/odoo/custom_addons:/mnt/custom-addons
    environment:
      - HOST=db
      - USER=${POSTGRES_DB_USER}
      - PASSWORD=${POSTGRES_DB_PASSWORD}
    networks:
      - obtech-odoo-internal-network
  db:
    image: postgres:15
    container_name: obtech_odoo_db
    restart: always
    volumes:
      - obtech-odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./data/db/shared_folder:/var/lib/postgresql/shared_folder
    environment:
      - POSTGRES_DB=${POSTGRES_DB_MAINTENANCE_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - obtech-odoo-internal-network
  pgadmin:
    image: elestio/pgadmin:REL-9_8
    container_name: obtech_odoo_db_admin
    depends_on:
      - db
    volumes:
      - obtech-odoo-pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    networks:
      - obtech-odoo-internal-network
volumes:
  obtech-odoo-db-data:
  obtech-odoo-pgadmin-data:
  obtech-odoo-data:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt:

networks:
  obtech-odoo-internal-network:
    driver: bridge
  
